"""
Django settings for neuraplay project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import redis



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!  
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "neuraplay-service-930102180917.us-central1.run.app",
    "neuraplay-service-hvqvt3ycnq-uc.a.run.app",
    ".run.app",  
    ".a.run.app", 
    ]

# # Override the default runserver command
# if 'runserver' in sys.argv:
#     # Auto-launch Daphne when runserver is called
#     import subprocess
#     import os
    
#     # Remove runserver from args to avoid Django's server
#     sys.argv.remove('runserver')
    
#     # Build and execute Daphne command
#     daphne_cmd = [
#         'daphne',
#         'neuraplay.asgi:application',
#         '--port', '8000', 
#         '--bind', '0.0.0.0'
#     ]
    
#     os.execvp('daphne', daphne_cmd)




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'analysis.apps.AnalysisConfig',
    'corsheaders',
    'channels'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://neuraplay-app-930102180917.us-central1.run.app"
]

# CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'neuraplay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'neuraplay.wsgi.application'

ASGI_APPLICATION = 'neuraplay.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# # neuraplay/settings.py
# # Add these to your existing settings

# # Celery Configuration
# CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Or your Redis URL
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'UTC'

# Celery Beat Schedule (this is the magic that makes it run automatically)
CELERY_BEAT_SCHEDULE = {
    'cleanup-expired-analyses-every-hour': {
        'task': 'analysis.tasks.cleanup_expired_analyses',
        'schedule': 3600.0,  # Every hour in seconds
        # Alternatively, use crontab format:
        # 'schedule': crontab(minute=0, hour='*/1'),  # Every hour at :00
    },
}



# ... your existing imports and base config ...

# Determine environment
IS_PRODUCTION = True #os.environ.get('PRODUCTION', 'false').lower() == 'true'

# Security settings for production
if IS_PRODUCTION:
    # DEBUG = False
    # ALLOWED_HOSTS = [
    #     "neuraplay-service-930102180917.us-central1.run.app",
    #     "localhost",
    #     "127.0.0.1",
    # ]
    
    # Use environment variable for Redis in production
    REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
else:
    DEBUG = True
    # ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
    REDIS_URL = 'redis://localhost:6379/0'

# Celery Configuration for production
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Channel layers for production
if IS_PRODUCTION:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }

# Remove the runserver override for production
# if not IS_PRODUCTION and 'runserver' in sys.argv:
#     if 'runserver' in sys.argv:
#         # Auto-launch Daphne when runserver is called
#         import subprocess
#         import os
        
#         # Remove runserver from args to avoid Django's server
#         sys.argv.remove('runserver')
    
#     # Build and execute Daphne command
#     daphne_cmd = [
#         'daphne',
#         'neuraplay.asgi:application',
#         '--port', '8000', 
#         '--bind', '0.0.0.0'
#     ]
    
#     os.execvp('daphne', daphne_cmd)
#     # ... your existing development runserver code ...


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PORT = int(os.environ.get("PORT", 8080))

STATIC_ROOT = os.path.join(BASE_DIR, "static")


